# Generated by Django 4.2.11 on 2024-04-21 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sku_api", "0002_skudata"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="skudata",
            unique_together={
                ("name", "location", "category", "department", "subcategory")
            },
        ),
    ]
